### ISSUE TITLE
Android 几乎不能用

### ISSUE THREAD

**Issue by nodejscss** [jpush/jpush-phonegap-plugin#289]
昨天第一次刚用jpush-phonegap-plugin, 发现如下几个问题：
1. android手机设置了自启动，但刚开机后不能收到推送通知，而是要输入密码手机解锁屏幕后才能收到推送通知；
2. android手机刚进入锁屏状态时还能收到推送通知，但十分钟左右后就收不到推送通知了，而是要解锁锁屏状态后能收到推送通知；
3. 刚进入锁屏状态时，还能收到推送通知，但，并不象iOS那样在锁屏上显示通知；
4. 在使用程序时，也能收到通知，没有找到设置成 “只有离开程序和锁屏时才收推送通知“；
5. 为解决上面的第2点，加入cordova-plugin-background-mode，锁屏后很久也能收到推送通知，但却与第1点冲突，即刚开机后，即使解锁屏幕也不能收到推送通知；另，cordova-plugin-background-mode 不能用在iOS，Apple拒绝，审核不过；
6. jpush-phonegap-plugin的通知声音小得听不见， 加入cordova-plugin-local-notifications使用洪亮的声音，但，程序立马闪退崩溃，单独使用cordova-plugin-local-notifications时，非常好。

请教如何解决以上问题。多谢！

**Comment by lhw5123** [comment]
1. 刚开机后收不到推送通知，因为通知服务没有起来。通知服务的唤醒依赖于Android 的锁屏/解锁等事件广播。
2. Android 进入锁屏状态后一段时间，应用服务基本都是会被杀掉的。
3. 在锁屏上显示通知只支持 Android 5.0 以上设备，而且不是所有 rom 都会默认在锁屏上显示应用通知。比如，小米和华为都需要在应用通知设置里设置是否在锁屏显示。
4. 没有「只有离开程序和锁屏时才收推送通知」这样的设置。
5. 锁屏后系统杀程序进程，你应用很难控制。
6. 通知声音不是插件控制的，是系统控制的。我这边用华为测试 demo 是正常的。

**Comment by nodejscss** [comment]
3. 我们用小米测试的，Android 7.1.1 ，在应用通知设置里设置了在锁屏时显示，不过锁屏时，有声音，但不象iOS那样在锁屏上显示通知条（亮屏）并自动消失；
4. 期待加入「只有离开程序和锁屏时才收推送通知」这样的设置。

谢谢！

**Comment by lhw5123** [comment]
小米的话，看一下在设置的「锁屏、密码和指纹」->「锁屏来通知时亮屏」有没有打开。
和具体应用的通知设置里有没有开启「锁屏通知」。
![screenshot_2017-11-13-13-53-29-301_com android se](https://user-images.githubusercontent.com/6531354/32712034-379e19dc-c87d-11e7-8584-f61e6c74ddab.png)
![screenshot_2017-11-13-13-53-58-020_com android se](https://user-images.githubusercontent.com/6531354/32712145-ef1e793a-c87d-11e7-98ed-af725cce6463.png)

**Comment by nodejscss** [comment]
在设置的「锁屏、密码和指纹」->「锁屏来通知时亮屏」是打开的， 
在具体应用的通知设置力也是开启的。

另外，还在设置的【授权管理】-》【应用权限管理】-》【允许应用在锁屏上显示】，
但，还是只有收到通知的很小的声音，没有亮屏显示通知条。

**Comment by nodejscss** [comment]
另外，期待能有播放指定洪亮的声音文件的设置，比如：www/resource/sound/beep.wav, http://domain.com/beep.wav

**Comment by nodejscss** [comment]
刚才有测试了多遍：
6. jpush-phonegap-plugin的通知声音小得听不见， 加入cordova-plugin-local-notifications使用洪亮的声音，但，程序立马闪退崩溃（android闪退，iOS没有），单独使用cordova-plugin-local-notifications时，非常好。

请教怎么解决。多谢！

**Comment by lhw5123** [comment]
能不能提供日志？ 发自网易邮箱大师 在2017年11月13日 21:47，nodejscss 写道： 刚才有测试了多遍： 6. jpush-phonegap-plugin的通知声音小得听不见， 加入cordova-plugin-local-notifications使用洪亮的声音，但，程序立马闪退崩溃（android闪退，iOS没有），单独使用cordova-plugin-local-notifications时，非常好。 请教怎么解决。多谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nodejscss** [comment]
日志怎么弄？

现在只能卸掉cordova-plugin-local-notification  。

**Comment by lhw5123** [comment]
就是应用崩溃时的日志，不然不好定位问题。
我这里用 jpush-phonegap-plugin 项目里的 demo，两个插件一起用，没出现崩溃。
cordova-plugin-local-notification 版本是 v0.8.4。

**Comment by nodejscss** [comment]
在事件onReceiveMessage里是没有触发的，只在事件onReceiveNotification有触发。

两种情况都闪退：
第一种，把cordova-plugin-local-notification（下面的代码）放在事件onReceiveNotification里，接收到推送消息时直接闪退：
var now = new Date().getTime(),
    _5_sec_from_now = new Date(now + 2 * 1000);
    // var sound = device.platform == 'Android' ? 'www/resource/media/beep.mp3' : 'www/resource/media/beep.wav';
    var sound = 'file://resource/media/beep.wav';
    // alert(_5_sec_from_now);
    // alert(sound);
    cordova.plugins.notification.local.schedule({
      id: 1,
      title: '通知',
      text: 'Alert',
      at: _5_sec_from_now,
      // every: 'minute',
      sound: sound,
      badge: 6
    });

第二种情况，单独把上面的代码用一个button人工点击执行也闪退，但卸掉jpush后，不闪退。

**Comment by lhw5123** [comment]
还是提供下日志，有日志直接就知道是什么问题了。另外你那段代码里不设置 sound，看还会不会崩溃。

**Comment by nodejscss** [comment]
怎么弄日志？

我们没装Android Studio, 因为刚开始时，其Gradle版本与下载的版本冲突，崩溃了，而且它是JAVA，很耗资源，就卸掉了，所以只安装了必要的Android SDK和build-tools.

而命令行 cordova run android, 打不出日志。请教不用Android Studio 如何打日志。

**Comment by lhw5123** [comment]
我按照你的代码帮你测了，日志里显示是 local-notification 插件里面出现了异常。你可以去那边 issue 里搜一下有没有类似问题。

```
java.lang.RuntimeException: Unable to start receiver de.appplant.cordova.plugin.localnotification.TriggerReceiver: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.hevin.jmessage/cache/localnotification/beep.wav exposed beyond app through Notification.sound
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3047)
  at android.app.ActivityThread.-wrap18(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.hevin.jmessage/cache/localnotification/beep.wav exposed beyond app through Notification.sound
  at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
  at android.net.Uri.checkFileUriExposed(Uri.java:2346)
  at android.app.NotificationManager.notifyAsUser(NotificationManager.java:300)
  at android.app.NotificationManager.notify(NotificationManager.java:284)
  at android.app.NotificationManager.notify(NotificationManager.java:268)
  at de.appplant.cordova.plugin.notification.Notification.showNotification(Notification.java:239)
  at de.appplant.cordova.plugin.notification.Notification.show(Notification.java:224)
  at de.appplant.cordova.plugin.notification.TriggerReceiver.onTrigger(TriggerReceiver.java:45)
  at de.appplant.cordova.plugin.localnotification.TriggerReceiver.onTrigger(TriggerReceiver.java:48)
  at de.appplant.cordova.plugin.notification.AbstractTriggerReceiver.onReceive(AbstractTriggerReceiver.java:75)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
  at android.app.ActivityThread.-wrap18(ActivityThread.java) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:154) 
  at android.app.ActivityThread.main(ActivityThread.java:6119) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by nodejscss** [comment]
好的。我去那边搜搜看。

非常感谢你！

**Comment by nodejscss** [comment]
为什么会这样？刚才发送通知，突然（AppKey和Master Secret没变化过）收不到了，
iOS也收不到，经检查，无法获取，在Xcode里一直拼命地打印如下信息：
JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:31.366211+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:32.395723+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:32.403639+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:33.421323+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:33.427051+0800 LooHooL[722:204404]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:34.449670+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:34.456474+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:35.476222+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:35.483196+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:36.506361+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:36.513340+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:37.536138+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:37.542918+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:38.569830+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:38.573695+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:39.600908+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:39.604950+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:40.643466+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:40.646848+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:41.709948+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:41.712554+0800 LooHooL[722:204404]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:42.903608+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:42.905371+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:43.955658+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:43.958801+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:44.985299+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:44.988062+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:46.011512+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:46.013874+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:47.034396+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:47.036512+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:48.061777+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:48.063556+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:49.087866+0800 LooHooL[722:204298]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:49.091241+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:42:49.591511+0800 LooHooL[722:205550]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:07.992308+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:07.995355+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:08.480611+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:11.769076+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:11.773500+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:12.235759+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:15.074297+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:15.077000+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:15.521289+0800 LooHooL[722:205736]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:17.638409+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:17.641819+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:18.067775+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:20.089953+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:20.092906+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:20.506773+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:22.484625+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:22.488367+0800 LooHooL[722:205736]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:22.880442+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:24.997587+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:25.000407+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:25.375599+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:27.863104+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:27.868947+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:28.225381+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:30.401491+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:30.409112+0800 LooHooL[722:205734]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:30.743560+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:32.967960+0800 LooHooL[722:205430]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:32.970989+0800 LooHooL[722:205735]  | JIGUANG | D - [JIGUANGService] Action - registrationID
2017-11-16 01:43:33.294432+0800 LooHooL[722:205733]  | JIGUANG | D - [JIGUANGService] Action - registrationID

**Comment by nodejscss** [comment]
为什么？为什么是“”不是合法的APP_KEY？不久前还好好的，怎么突然就不灵了？

2017-11-16 02:07:06.551970+0800 LooHooL[746:212917]  | JIGUANG | E - [JIGUANGAlert] ERROR
“”不是合法的APP_KEY。
（有关APP_KEY的说明请参考开发文档“SDK集成指南”。https://docs.jiguang.cn/jpush/client/iOS/ios_guide_new/
2017-11-16 02:07:06.552790+0800 LooHooL[746:212917]  | JIGUANG | E - [JIGUANGService] 请检查"setupWithOption:appKey:channel:apsForProduction:"方法的参数值

**Comment by nodejscss** [comment]
找到导致jpush不能用的问题了，根据 
http://cordova.apache.org/blog/ 
的Plugins Release，10 Nov 2017 - by Steve Gill，更新了几个plugin，然后jpush就说不是合法的APP_KEY了，恢复到原来的plugin，就又可以了，估计是jpush与cordova-plugin-file和device不兼容，所致。

**Comment by nodejscss** [comment]
刚才又发现JPush的下面的函数在iOS有问题（alertContent = event.aps.alert;），在Android闪退：
var onReceiveNotification = function(event) {
    try {
      var alertContent;
      if (device.platform == "Android") {
        alertContent = event.alert;
      } else {
        alertContent = event.aps.alert;
      }
      // alert(alertContent+'---->onReceiveNotification');
    } catch (exception) {
      alert(2);
      alert(exception)
    }
  };

**Comment by nodejscss** [comment]
刚才忘记说了，是Jpush与cordova-plugin-local-notification的alertContent = event.aps.alert;有问题

**Comment by lhw5123** [comment]
@nodejscss 在 iOS 有问题，具体是什么问题。有没有日志。

**Comment by nodejscss** [comment]
就是alertContent = event.aps.alert; 抛出异常alert(exception)；可能是event是undefined抛出异常。

由于android的声音太小，我本来是要用cordova-plugin-local-notification播放大声音的,但不成功，测试时拿错了手机，iOS就抛出异常了。

要是jpush也能播放指定声音文件就好了，它们说声音太小，快要把我折腾死了。

**Comment by longdw** [comment]
华为手机上该插件能用？非常不稳定吧，而且一退到后台基本收不到消息，小米手机上没发现问题。华为P9 10建议你们看下。
