### ISSUE TITLE
使用ionic3 集成jpush极光推送出错

### ISSUE THREAD

**Issue by nixiaozi** [jpush/jpush-phonegap-plugin#311]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境

* 插件版本:
* 平台（Android / iOS）: Android 7.0.0
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```):
  Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Ionic Version (if using Ionic): 3.19.0

## 期望效果

新建一个ionic3的项目并且导入JPush，希望能过程序正常运行

## 实际效果

在android想要在Android手机上调试运行时出错

## 重现步骤

  1. 首先使用命令创建项目 “ionic start testdemo tabs” 。
  2. ...? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
  3. ...? Install the free Ionic Pro SDK and connect your app? Yes
  4. ...? Which app would you like to link Nevermind
  5. 然后cd .\testdemo\ 转到项目使用命令“ ionic cordova plugin add jpush-phonegap-plugin --variable APP_KEY=your_jpush_appkey”
来添加引用
  6. 然后使用命令“npm install --save @jiguang-ionic/jpush”
来添加ionic native的引用
  7. 然后添加app对jpush的引用。最后运行“ionic cordova run android --device” 就会报错

## 背景

你尝试做过些什么？
我试着重新安装了Android flatform 但是没有解决问题并且出现了更多的到找不到'..\platforms\android\AndroidManifest.xml'文件的问题
我试着修改插件的config.xml文件的Android配置但是没有用。

## Debug logs

包括 Android 或 iOS 的日志：
PS E:\InoicProject\testdemo> ionic cordova run android --device
> cordova platform add android --save
Using cordova-fetch for cordova-android@~7.0.0

Adding android project...

Creating Cordova project for the Android platform:

        Path: platforms\android
        Package: io.ionic.starter
        Name: testdemo
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected

Android Studio project detected

Installing "jpush-phonegap-plugin" for android

Installing "cordova-plugin-device" for android

Installing "cordova-plugin-jcore" for android
Failed to install 'jpush-phonegap-plugin': Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\testdemo\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\testdemo\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

(node:3420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
(node:3420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Running app-scripts build: --platform android --target cordova
[18:08:30]  build dev started ...
[18:08:30]  clean started ...
[18:08:30]  clean finished in 4 ms
[18:08:30]  copy started ...
[18:08:30]  deeplinks started ...
[18:08:30]  deeplinks finished in 28 ms
[18:08:30]  transpile started ...
[18:08:33]  transpile finished in 3.32 s
[18:08:33]  preprocess started ...
[18:08:33]  preprocess finished in 1 ms
[18:08:33]  webpack started ...
[18:08:33]  copy finished in 3.54 s
[18:08:40]  webpack finished in 6.50 s
[18:08:40]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[18:08:41]  sass finished in 1.81 s
[18:08:41]  postprocess started ...
[18:08:41]  postprocess finished in 10 ms
[18:08:41]  lint started ...
[18:08:41]  build dev finished in 11.86 s
> cordova run android --device
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project

[18:08:45]  lint finished in 3.29 s
Installing "ionic-plugin-keyboard" for android

Failed to install 'ionic-plugin-keyboard': Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\testdemo\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\testdemo\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

Failed to restore plugin "ionic-plugin-keyboard" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android
Failed to install 'cordova-plugin-whitelist': Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\testdemo\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\testdemo\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

Failed to restore plugin "cordova-plugin-whitelist" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android

Failed to install 'cordova-plugin-splashscreen': Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\testdemo\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\testdemo\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

Failed to restore plugin "cordova-plugin-splashscreen" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for android

Failed to install 'cordova-plugin-ionic-webview': Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (E:\InoicProject\testdemo\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (E:\InoicProject\testdemo\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (E:\InoicProject\testdemo\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_cordova-lib@8.0.0@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\QT02\AppData\Roaming\npm\node_modules\cordova\node_modules\_q@1.0.1@q\q.js:816:30)

Failed to restore plugin "cordova-plugin-ionic-webview" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\AndroidManifest.xml'
cp: copyFileSync: could not write to dest file (code=ENOENT):E:\InoicProject\testdemo\platforms\android\res\xml\config.xml

Parsing E:\InoicProject\testdemo\platforms\android\res\xml\config.xml failed
(node:17288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'E:\InoicProject\testdemo\platforms\android\res\xml\config.xml'
(node:17288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ERROR] An error occurred while running cordova run android --device (exit code 1).

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lhw5123** [comment]
目前插件还未支持 cordova-android 7.0.0，因此添加 android platform 时，需要使用之前的版本。比如 6.4.0。

**Comment by nixiaozi** [comment]
@lhw5123   降低android platform的版本后就没有问题了。谢谢
