### ISSUE TITLE
调用插件成功的方法不回调

### ISSUE THREAD

**Issue by ygeng** [jpush/jpush-phonegap-plugin#383]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境 

* 插件版本:
* 平台（Android / iOS）: Android
* Cordova version (```cordova -v```): 8.1.2
* Cordova platform version (```cordova platform ls```): android 7.1.1
* Ionic Version (if using Ionic)

## 期望效果

在调用插件的时候，希望在方法执行成功的时候做一些操作，比如设置别名成功以后，将别名传给后台。

## 实际效果

按照文档调用插件，成功的时候所有的成功回调都不调用，失败的时候失败回调是会回调的。比如设置别名：
```
window.JPush.setAlias({sequence: 1, alias: 'bbbb71881993839sisk'}, function(result){
        console.log('success');
    }, function(error){
        console.log('failure');
});
```
其实已经设置成功了，在极光后台可以对这个别名推送成功了，但是这个“success”就是不输出，在里面alert也没效果

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by JoshLipan** [comment]
官方例子测试[setAlias](https://github.com/jpush/jpush-phonegap-plugin/blob/master/example/index.html#L154)是有成功返回的，你用的插件版本是什么？参考demo调用下
![image](https://user-images.githubusercontent.com/16323137/48691536-d9f14d80-ec0d-11e8-8ace-10b5a41a4f7b.png)

**Comment by ygeng** [comment]
跟demo的方式好像一样的，我的插件版本是3.4.3，我更新到3.5.1试了下，也还是不回调。
出现这种情况，一般有哪些可能呢？

**Comment by ygeng** [comment]
我的所有监听事件也不回调

**Comment by JoshLipan** [comment]
这不确定是什么问题，我们没法复现，重新生成 Android 平台试试呢

**Comment by ygeng** [comment]
![image](https://user-images.githubusercontent.com/13791355/48700355-c69eac00-ec26-11e8-98b5-567b5413a0ec.png)

这里直接调callbackContext.success()可以吗？

**Comment by ygeng** [comment]
我在`JPushEventReceiver`中的`onAliasOperatorResult()`方法打断点，发现确实调了`success()`方法，但是js回调方法不执行

**Comment by ygeng** [comment]
点击通知的日志如下：
```
D/CordovaWebViewImpl: >>> loadUrl(javascript:window.plugins.jPushPlugin.receiveNotificationInAndroidCallback({"title":"大湖车务","alert":"open notification test","extras":{"cn.jpush.android.ALERT_TYPE":"7","cn.jpush.android.NOTIFICATION_ID":530187139,"cn.jpush.android.MSG_ID":"54043197895993402","cn.jpush.android.ALERT":"open notification test","cn.jpush.android.EXTRA":{}}});)
```
会报这样的错误：
```
2018-11-20 09:16:43.561 26625-26625/ W/Bundle: Key platform expected String but value was a java.lang.Byte.  The default value <null> was returned.
2018-11-20 09:16:43.564 26625-26625/ W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1130)
        at android.content.Intent.getStringExtra(Intent.java:7147)
        at cn.jiguang.cordova.push.JPushReceiver.getNotificationExtras(JPushReceiver.java:80)
        at cn.jiguang.cordova.push.JPushReceiver.handlingNotificationOpen(JPushReceiver.java:47)
        at cn.jiguang.cordova.push.JPushReceiver.onReceive(JPushReceiver.java:30)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3223)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by JoshLipan** [comment]
你先用demo测试下有没有问题，有问题的话[打开debug模式](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#setdebugmode)抓取log提供下

**Comment by ygeng** [comment]
demo是好的，但是我看demo设置和获取别名的时候，会打印很多日志，但是我的就只有这两行：

![image](https://user-images.githubusercontent.com/13791355/48753822-66f9dc80-ecca-11e8-82ba-213b98be5d97.png)

**Comment by JoshLipan** [comment]
同个项目环境下怎么会出现两种不一样的表现？还是demo你是新开的项目测试的？
1.先确认版本：3.5.1 版本需要对应安装 cordova-plugin-jcore@1.2.6
2.alias 和 tag 的 sequence 参数是标识一次操作的唯一性，每次设置不要重复sequence
3.log不要只截取你认为重要的信息，[打开debug模式](https://github.com/jpush/jpush-phonegap-plugin/blob/master/doc/Common_detail_api.md#setdebugmode)后直接抓取原生log文件提供就行：adb logcat -v time ->a.log
