### ISSUE TITLE
cordova build android找不到Entitlements-Debug.plist文件

### ISSUE THREAD

**Issue by huxiamei** [jpush/jpush-phonegap-plugin#384]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**
config file */Entitlements-Debug.plist requested for changes not found at F:\linyungit\app\dev\platforms\android\*\Entitlements-Debug.plist, ignoring
config file */Entitlements-Release.plist requested for changes not found at F:\linyungit\app\dev\platforms\android\*\Entitlements-Release.plist, ignoring
Merging project's config.xml into platform-specific android config.xml
Unhandled "error" event. (Parsing F:\linyungit\app\dev\platforms\android\res\xml\config.xml failed)
Error: Unhandled "error" event. (Parsing F:\linyungit\app\dev\platforms\android\res\xml\config.xml failed)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at EventEmitter.module.exports.emit (F:\linyungit\app\dev\platforms\android\cordova\node_modules\cordova-common\src\events.js:68:30)
    at new ConfigParser (F:\linyungit\app\dev\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:34:16)
    at updateConfigFilesFrom (F:\linyungit\app\dev\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (F:\linyungit\app\dev\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (F:\linyungit\app\dev\platforms\android\cordova\Api.js:192:45)
    at C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:105:36
    at _fulfilled (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30)
[ERROR] An error occurred while running subprocess cordova.

## 你的运行环境
* 插件版本:
jpush-phonegap-plugin 3.5.1
* 平台（Android / iOS）:
android
* Cordova version (```cordova -v```):
cordova 81.2
* Cordova platform version (```cordova platform ls```):
android 7.1.1
* Ionic Version (if using Ionic)
 ionic CLI PRO 4.4.0

## 期望效果
正常打包

## 实际效果
打包失败

## 重现步骤

  1. npm i 
  2. ionic cordova platform add android@7.1.1
  3. ionic cordova build android

## 背景
发现项目从android6升级到android7后platform下的路径变化了

## Debug logs

包括 Android 或 iOS 的日志：

* iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat
config file */Entitlements-Debug.plist requested for changes not found at F:\linyungit\app\dev\platforms\android\*\Entitlements-Debug.plist, ignoring
config file */Entitlements-Release.plist requested for changes not found at F:\linyungit\app\dev\platforms\android\*\Entitlements-Release.plist, ignoring
Merging project's config.xml into platform-specific android config.xml
Unhandled "error" event. (Parsing F:\linyungit\app\dev\platforms\android\res\xml\config.xml failed)
Error: Unhandled "error" event. (Parsing F:\linyungit\app\dev\platforms\android\res\xml\config.xml failed)
    at EventEmitter.emit (events.js:186:19)
    at EventEmitter.module.exports.emit (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:71:17)
    at EventEmitter.module.exports.emit (F:\linyungit\app\dev\platforms\android\cordova\node_modules\cordova-common\src\events.js:68:30)
    at new ConfigParser (F:\linyungit\app\dev\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:34:16)
    at updateConfigFilesFrom (F:\linyungit\app\dev\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (F:\linyungit\app\dev\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (F:\linyungit\app\dev\platforms\android\cordova\Api.js:192:45)
    at C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:105:36
    at _fulfilled (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\hxm\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30)
[ERROR] An error occurred while running subprocess cordova.

**Comment by JoshLipan** [comment]
这个错误和极光插件有什么联系？

**Comment by huxiamei** [comment]
> 这个错误和极光插件有什么联系？

我全局搜索引用Entitlements-Debug.plist的文件，发现是极光推送的插件下的

**Comment by huxiamei** [comment]
> 你卸载 jpush 能正常编译吗

卸载了，还是会报错，不是极光推送的原因。可能是AndroidManifest.xml文件路径变了导致的。谢谢解答
